### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by rmcgibbo** [manylinux/manylinux#1]
Hey Nathaniel. Thanks for inviting me.

Do you want to do discussion here or on the google group?

**Comment by rmcgibbo** [comment]
> I (= njs) am thinking maybe our rule for determining whether a system is considered to be manylinux1-compatible should be:

> the regular wheel platform tag (which is distutils.util.get_platform()) starts with the string "linux"
> the interpreter is linked to a version of glibc that is >= the one in CentOS 5
> we check some file in /etc/pypa/compatibility or something and find that there is no flag in there specifically saying "this platform is not manylinux1 compatible"

One of the potential problems with just checking the name / version of the distro that you're on (I assume that's what you mean by checking `/etc/pypa/compatibility`) is that the wheel-builder could potentially have done an infinite possible sequence of `{apt-get,yum} installs`, so even though the wheel was built on on CentOS 5 or whatever, it might be linked against any obscure package that's known to the package manager.

**Comment by rmcgibbo** [comment]
> In principle one could get much fancier trying to track down every library that's in the spec and checking its version etc., but keep in mind that the companies distributing Python-on-Linux distributions are using the rule "if it's linux then it's compatible", and this is actually working for them, and the idea here is to use the same baseline platform as they do.

I think I have this basically working now. The policy questions might be a little challenging, but the technical aspects of it are pretty simple. Essentially the flow is 
 * Unpack wheel, and find all the ELF files
 * Check their DT_NEEDED records for shared library dependencies
   * If needed libraries are either in the tag's "whitelist" or resolve via RPATH/RUNPATH to something inside the wheel, then we're good.
 * Check each of the ELF files for external versioned symbols (GLIBC, CXXABI, etc), and check whether the versions are consistent with the the tag's allowable version symbols.

**Comment by rmcgibbo** [comment]
So I suspect the challenging part is just deciding on [the policy](https://github.com/rmcgibbo/deloc8/blob/master/deloc8/policy/policy.json#L15-L23)

**Comment by njsmith** [comment]
I'm used to doing discussion in mailing lists and using issue trackers to keep track of discrete issues, so that was my default, but I guess we could do either if anyone else has a preference...

Regarding the other stuff: I'm not talking about the wheel builder there, I'm talking about the wheel installer that has found a valid manylinux1 wheel and has to decide whether it should try installing it. Totally different situations :-). And I meant literally some new config file in `/etc` that pip would look at to check whether the distro thinks that the libraries it provides are ABI-compatible with RHEL5. (Even if right now all distros are in fact compatible, maybe some future distros will not be.)

**Comment by rmcgibbo** [comment]
> I'm not talking about the wheel builder there, I'm talking about the wheel installer that has found a valid manylinux1 wheel and has to decide whether it should try installing it.

Oh, sorry. I should have realized that. Okay. I agree then.

**Comment by rmcgibbo** [comment]
> I'm used to doing discussion in mailing lists

Okay, I'm fine with moving to the google group.
